version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    open-pull-requests-limit: 64
    groups:
      orpc:
        patterns:
          - "@orpc/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      vueuse:
        patterns:
          - "@vueuse/*"
      nx:
        patterns:
          - "nx"
          - "@nx/*"
      drizzle:
        patterns:
          - "drizzle*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
