services:
  drizzle-gate:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle-gate
    restart: always
    network_mode: host
    environment:
      - PORT=4983
      - STORE_PATH=/app
      - MASTERPASS=
    volumes:
      - ./gateway:/app
